#!/bin/bash

rm alex_exp.card;
rm networkadmin.card;;
rm restadmin.card;

composer card delete -c alex@supply-chain
composer card delete -c restadmin@supply-chain
composer card delete -c admin@supply-chain

composer network install -c PeerAdmin@hlfv1 --archiveFile supply-chain@0.0.24.bna

composer network start -c PeerAdmin@hlfv1 --networkName supply-chain --networkVersion 0.0.24 --networkAdmin admin --networkAdminEnrollSecret adminpw --file networkadmin.card

composer card import -f networkadmin.card

composer network ping -c admin@supply-chain

composer participant add -c admin@supply-chaine -d '{"$class":"org.hyperledger.composer.system.NetworkAdmin", "participantId":"restadmin"}'

composer identity issue -c admin@supply-chain -f restadmin.card -u restadmin -a "resource:org.hyperledger.composer.system.NetworkAdmin#restadmin"

sed -e 's/localhost:7051/peer0.org1.example.com:7051/' -e 's/localhost:7053/peer0.org1.example.com:7053/' -e 's/localhost:7054/ca.org1.example.com:7054/'  -e 's/localhost:7050/orderer.example.com:7050/'  < $HOME/.composer/cards/restadmin@supply-chain/connection.json  > /tmp/connection.json && cp -p /tmp/connection.json $HOME/.composer/cards/restadmin@supply-chain/ 

composer participant add -c admin@supply-chain -d '{"$class":"org.catena.Customer","UserId":"1", "name":"Alex","phoneNumber":"0723489364", "email":"asloe@aslkas.com","phoneNumber":"10 fake street"}'
composer identity issue -c admin@supply-chain -f alex.card -u alex -a "resource:org.catena.Customer#1"
composer card import -f alex.card


sed -e 's/localhost:7051/peer0.org1.example.com:7051/' -e 's/localhost:7053/peer0.org1.example.com:7053/' -e 's/localhost:7054/ca.org1.example.com:7054/'  -e 's/localhost:7050/orderer.example.com:7050/'  < $HOME/.composer/cards/alex@supply-chain/connection.json  > /tmp/connection.json && cp -p /tmp/connection.json $HOME/.composer/cards/alex@supply-chain/

composer card export -f alex_exp.card -c alex@supply-chain ; rm alex.card